[package]
name = "lycaon"
version = "0.1.0"
authors = ["Hamish Hutchings <moredhel@aoeu.me>"]

[dependencies]
# pinned
ring = "0.11.0" # cookie depends on this version

rocket = "0.3.2"
rocket_codegen = "0.3.2"
rocket_contrib = "0.3.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
uuid = { version = "0.5.1", features = ["v4", "rustc-serialize"] }
log = "0.3"
slog = "2.0.12"
slog-term = "2.2.0"
slog-async = "2.1.0"
fern = "0.4"
chrono = "0.4.0"
ctrlc = { version = "3.0", features = ["termination"] }
hostname = "^0.1"

# grpc
# grpc            = "0.*"
# protobuf        = "1.*"
# futures         = "0.1"
# futures-cpupool = "0.1"

[build-dependencies]
capnpc = "0.8.7"
