[package]
name = "lycaon"
version = "0.1.0"
authors = ["Hamish Hutchings <moredhel@aoeu.me>"]

[dependencies]
# pinned
ring = "0.11.0" # cookie depends on this version

rocket = "0.3.2"
rocket_codegen = "0.3.2"
rocket_contrib = "0.3.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
uuid = { version = "0.5.1", features = ["v4", "rustc-serialize"] }
log = "0.3"
fern = "0.4"
chrono = "0.4.0"
