[grpc]
[grpc.listen]
host = "localhost"
port = 51000
[grpc.bootstrap]
host = 'localhost'
port = 3117
[web.listen]
host = "::"
port = 8000
[tls]
use_tls = true
certs = "./tmp/certs/ca.crt"
key = "./tmp/certs/domain.key"
