[grpc]
[grpc.listen]
host = "0.0.0.0"
port = 51001
[grpc.bootstrap]
host = "0.0.0.0"
port = 51001
[web.listen]
host = "0.0.0.0"
port = 8000
[tls]
use_tls = true
certs = "./certs/ca.crt"
key = "./certs/domain.key"
