apiVersion: apps/v1
kind: Deployment
metadata:
  name: trow-deploy
spec:
  selector:
    matchLabels:
      app: trow
  template:
    metadata:
      labels:
        app: trow
    spec:
      containers:
      - name: trow-pod
        image: containersol/trow:default
        args: ["--no-tls", "-n", "registry.trow.io"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /data
          name: data-vol
      volumes:
        - name: data-vol
          emptyDir: {}
