apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trow-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: registry.trow.io
      http:
        paths:
          - backend:
            serviceName: trow-svc
            servicePort: 443
  tls: 
    - hosts:
        - registry.trow.io
      secretName: trow-registry-tls
