apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trow-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: registry.trow.io
      http:
        paths:
          - path: /
            backend:
              serviceName: trow-svc
              servicePort: 8000
  tls: 
    - hosts:
        - registry.trow.io
      secretName: trow-registry-tls
