apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trow-example

bases:
  - ../cert-manager-nginx

secretGenerator:
  - name: trow-pass
    literals:
    - docker-server=example.registry.com
    - docker-username=example
    - docker-password=s3cr3tp@55
  - name: trow-cred
    type: docker-registry
    literals:
    - docker-server=example.registry.com
    - docker-username=example
    - docker-password=s3cr3tp@55

patchesJson6902:
  - path: patch-ingress-host.yaml
    target:
      kind: Ingress
      name: trow-ingress
      group: extensions
      version: v1beta1
  - path: patch-trow-arg.yaml
    target:
      kind: Deployment
      name: trow-deploy
      group: apps
      version: v1

#    - path: patch-validator-domain.yaml
#      target:
#        kind: ValidatingWebhookConfiguration
#        name: trow-validator
#        group: admissionregistration.k8s.io
#        version: v1
